(function(){var h=void 0,k=true,l=null,m=false,o,p=this;function aa(a){var b=s;function c(){}c.prototype=b.prototype;a.z=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ba(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function t(a,b){var c="",d=ca(encodeURIComponent(a));d.splice(b||5,d.length);v(d,function(a,b){var d;d=b;if(d==0)d="A";else{d>>>=0;for(var i="",j;d>0;)j=d%64,i="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(j)+i,d>>>=6;d=i}c+=d});return c}
function ca(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,g=3285377520,i=[],j,q,r,x,C,I=Math.ceil((a.length/4+2)/16),E=[I],u=0,n;u<I;u++){E[u]=[];for(j=0;j<16;j++)E[u][j]=a.charCodeAt(u*64+j*4)<<24|a.charCodeAt(u*64+j*4+1)<<16|a.charCodeAt(u*64+j*4+2)<<8|a.charCodeAt(u*64+j*4+3)}u=(a.length-1)*8;a=I-1;E[a][14]=Math.floor(u/Math.pow(2,32));E[a][15]=u&4294967295;for(u=0;u<I;u++){for(n=0;n<16;n++)i[n]=E[u][n];
for(n=16;n<80;n++)i[n]=(i[n-3]^i[n-8]^i[n-14]^i[n-16])<<1|(i[n-3]^i[n-8]^i[n-14]^i[n-16])>>>31;a=c;j=d;q=e;r=f;x=g;for(n=0;n<80;n++)C=Math.floor(n/20),C=(a<<5|a>>>27)+(C==0?j&q^~j&r:C==1?j^q^r:C==2?j&q^j&r^q&r:j^q^r)+x+b[C]+i[n]&4294967295,x=r,r=q,q=j<<30|j>>>2,j=a,a=C;c=c+a&4294967295;d=d+j&4294967295;e=e+q&4294967295;f=f+r&4294967295;g=g+x&4294967295}return[c,d,e,f,g]}
function ea(a){var b=l;if(a){for(var b=l,a=document.getElementsByTagName("link"),c=0,d=a.length;c<d;++c)if(a[c].rel=="canonical")b=a[c].href,b=b.substring(b.indexOf("/",9));if(b)return b}c=p.location;b=c.pathname+(c.search||"");b=b.replace(/PHPSESSID=[^&]+/,"");a=/&utm_[^=]+=[^&]+/ig;(c=a.exec(c.search))&&(b=b.replace(a,""));a=/\?utm_[^=]+=[^&]+(.*)/i;(c=a.exec(b))&&(b=b.replace(a,c[1]!=""?"?"+c[1]:""));return b}function w(a,b){return function(){a.apply(b,arguments)}}
function y(a){return a.replace(/^www\./,"")}function z(a,b,c){a.addEventListener?a.addEventListener(b,c,m):a.attachEvent&&a.attachEvent("on"+b,c)}function fa(a,b){var c=p;c.removeEventListener?c.removeEventListener(a,b,m):c.detachEvent&&c.detachEvent("on"+a,b)}function A(a){return typeof a=="number"}function B(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function D(){return(new Date).getTime()}function F(a){return encodeURIComponent(a)}
function ga(a,b){if(!(a&&a.constructor===Object)||!(b&&b.constructor===Object))return a===b;var c=0,d=k;v(a,function(a,e){c++;return d=e===b[a]});if(!d)return m;var e=0;v(b,function(){e++});return c===e}function v(a,b){if((!!a&&a.constructor===Object)===k)for(var c in a){if(a.hasOwnProperty(c)&&b(c,a[c])===m)break}else{c=a.length;for(var d=0;d<c;d++)if(b(d,a[d])===m)break}}function ha(a,b){var c=[];v(a,function(a,e){b(e)&&c.push(e)});return c}
function ia(a){(!!a&&a.constructor===Object)===k&&(a="");var b={};v(a.split("&"),function(a,d){var e=d.split("::");e.length===2&&(b[decodeURIComponent(e[0])]=decodeURIComponent(e[1]))});return b}
function ja(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,g=a.length;f<=g;f++)c[0][f]=f;for(var i,j,q,d=1;d<=e;d++)for(f=1;f<=g;f++)i=d-1,j=f-1,q=c[i][j],b.charAt(i)==a.charAt(j)?c[d][f]=q:(j=c[d][j]+1,i=c[i][f]+1,q+=2,c[d][f]=Math.min(j,i,q));return c[b.length][a.length]};var G={},ka=1;function H(a,b,c){ka++;G[a]=G[a]||{};G[a][ka]=[b,c];return ka}function J(a){if(typeof a==="string")G[a]=h,delete G[a];else if(A(a)){var b=k;v(G,function(c,d){v(d,function(c){if(parseInt(c,10)===a)return d[c]=h,delete d[c],b=m});return b})}}function K(a,b){if(G[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];v(G[a],function(a,b){var f,g;b&&b.length===2&&(f=b[0],g=b[1],f.apply(g,c))})}};function L(){this.O=this.B=l;this.Q=[];la(this,p,"onscroll");la(this,document.body,"onkeydown");la(this,document.body,"onmousemove");this.h()}L.prototype.h=function(){this.J={};this.f=0;ma(this);this.J.onmousemove=D()};function ma(a){a.ha&&clearInterval(a.ha);a.pa();a.ha=setInterval(w(a.pa,a),1E3)}function na(a){for(var b=0,c=a.Q.length;b<c;b++)if(oa(a,a.Q[b],5E3))return k;return m}
function la(a,b,c){var d=b[c]||function(){};a.Q.push(c);b[c]=function(b){d.apply(this,arguments);if(b&&c=="onkeydown"){var f=b.keyCode?b.keyCode:b.which;if(f==32||f>36&&f<41){a.J.onscroll=D();return}}a.J[c]=D();a.B===l&&a.ga();a.O!==l&&p.clearTimeout(a.O);a.O=p.setTimeout(w(a.ga,a),100)}}L.prototype.ga=function(){var a=this;this.B=p.setTimeout(function(){p.clearTimeout(a.B);a.B=l},100);K("activity")};function oa(a,b,c){a=a.J[b];if(a===h)return m;a=D()-a;return a<=(c||15E3)&&a>=0}
L.prototype.pa=function(){na(this)&&this.f++};function pa(a){var b=a.f;a.f=0;ma(a);return b};var qa=/[?&]__cb_debug=/i;function ra(){};function sa(){this.Y=k;ta(this,"focus","focusin",this.Da);ta(this,"blur","focusout",this.Ca)}sa.prototype.Da=function(){this.Y=k};sa.prototype.Ca=function(){this.Y=m};function ta(a,b,c,d){a=w(d,a);window.addEventListener?window.addEventListener(b,a,m):document.attachEvent&&document.attachEvent(c,a)};function ua(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function va(a,b){var c=l;b&&(c=b.getAttribute(a));if(c===l){var d=ua(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}function wa(a,b,c){return a===h?m:c===h&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?m:wa(a.parentNode,b,c)}
function xa(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=ua("data-cb-scroll-element"))&&c.length)return c[0][b];if(A(p[a]))return p[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function M(a){return xa("Y","Top",a)}function ya(a){var b=document;return b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0}function N(){return ya("Height")}
function O(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function P(){return O("Height")};function Q(a){var b=a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1)for(var a=a.getElementsByTagName("iframe"),d,e,f=0,g=a.length;f<g;f++)if(d=a[f].offsetHeight,e=a[f].offsetWidth,d>1&&e>1){b=d;c=e;break}return{height:b,width:c}}function za(a,b){var c,d;if(b){var e=Q(b);c=e.width;d=e.height}else c=ya("Width"),d=N();var f=Q(a),e=f.height,f=f.width,g=R(a,b),i=g.y,g=g.x;c=Math.min(g+f,f,c-g);d=Math.min(i+e,e,d-i);return c<0||d<0?m:c*d>0.5*f*e}
function R(a,b,c){for(var d=a.offsetLeft,e=a.offsetTop,f=m,g=c?0:xa("X","Left",h),i=c?0:M(),j=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===j)d+=a.offsetLeft,e+=a.offsetTop,j=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(S(a,"position")==="fixed"){f=k;break}a=a.parentElement}c||(d-=b?b.scrollLeft:g,e-=b?b.scrollTop:i);f&&(d+=g,e+=i);return{x:d,y:e}}
function S(a,b){var c;c=p.getComputedStyle?(c=p.getComputedStyle(a,l))&&(c[b]||c.getPropertyValue(b)):a.currentStyle?a.currentStyle[b]:a.style&&a.style[b];return c||""};function Aa(a,b,c,d){this.e=a;this.r=a.getAttribute("data-cb-ad-id")||a.id||"";this.R=b;this.I=c;this.sa=d;this.F=this.G="";this.X=m;this.n=l;this.H=0;this.ea=setInterval(w(this.qa,this),Ba);this.qa()}var Ba=1E3;function Ca(a,b,c,d){a.F=b;a.G=c;a.X=!!d;K("forcePing")}o=Aa.prototype;o.p=function(a){var b={id:this.r,engagedSeconds:this.H,campaignId:this.F,creativeId:this.G};if(a)return b;var a=Q(this.e),c=R(this.e,h,k);b.positionLeft=c.x;b.positionTop=c.y;b.width=a.width;b.height=a.height;return b};
function Da(a){for(var b=a.I.Y,a=a.e,c=k,d=a.parentElement;d&&c;){var e;var f=d;if(f.scrollHeight===f.clientHeight&&f.scrollWidth===f.clientWidth)e=m;else{e=S(f,"overflow");var g=S(f,"overflow-x"),f=S(f,"overflow-y");e=e==="auto"||e==="scroll"||g==="auto"||g==="scroll"||f==="auto"||f==="scroll"}e&&(c=za(a,d));d=d.parentElement}a=c&&za(a,l);return b&&a}o.qa=function(){var a=Ba/1E3;na(this.R)&&Da(this)&&(this.H+=a,this.H===1&&K("forcePing"),K("adEngaged",this.p(k),this.e));this.sa&&Ea(this)};
o.M=function(){if(!this.X){var a=this.e,b=va("data-cb-campaign-id",a)||"",a=va("data-cb-creative-id",a)||"";b===this.F&&a===this.G||Ca(this,b,a)}};
function Ea(a){function b(a,b,c){var d=document.createElement("div"),e=document.createElement("span");e.setAttribute("style","font-weight: bold;");e.textContent=a;d.textContent=b;d.insertBefore(e,d.firstChild);c.appendChild(d)}var c=a.e;if(c){var d;if(a.n)d=document.getElementById(a.n);else{a.n="engagementLog-"+a.r+"-"+Math.floor(Math.random()*1E3);d=document.createElement("div");d.setAttribute("id",a.n);document.body.appendChild(d);var e=c.getAttribute("style")||"",f=S(c,"position"),f=f==="fixed"||
f==="absolute"||f==="relative"?"":"position: relative;";e+="box-shadow: 0px 0px 0px 3px #49A2DC; z-index: 2000;"+f;c.setAttribute("style",e);var g="box-shadow: 0px 0px 0px 3px #5BC3BD, 10px 5px 5px #C8DAE8; z-index: 2000;"+f;d.onmouseover=function(){c.setAttribute("style",g)};d.onmouseout=function(){e?c.setAttribute("style",e):c.removeAttribute("style")}}d.innerHTML="";var i=R(c),f=i.y,i=i.x;f+=M();i+=xa("X","Left",h);d.setAttribute("style","background-color: #F1F7FB; z-index: 9000000; position: absolute; padding: 10px; border-radius: 5px; font-size: 12px; color: #658BA1; border: 1px solid #C8DAE8; margin: 3px; font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif; top: "+
f+"px; left: "+i+"px;");f=a.p();b("Ad Name: ",f.id+" ["+f.width+"x"+f.height+"]",d);(i=f.campaignId)&&b("Campaign: ",i,d);(i=f.creativeId)&&b("Creative: ",i,d);d.appendChild(document.createElement("br"));var i=na(a.R),j="Out Of View";Da(a)&&(j=i?"Engaged In View":"In View");b(j,"",d);b("Engaged Time: ",f.engagedSeconds+" seconds",d)}}o.reset=function(){this.H=0;this.G=this.F="";this.X=m};
o.U=function(){if(this.ea)clearInterval(this.ea),this.ea=l;this.I=this.R=this.e=l;if(this.n){var a=document.getElementById(this.n);(a.parentElement?a.parentElement:a.parentNode).removeChild(a)}};function Fa(a){var b={};if(a){a.charAt(0)=="?"&&(a=a.substring(1));for(var a=a.replace("+"," "),a=a.split(/[&;]/g),c=0,d=a.length;c<d;c++){var e=a[c].split("=");b[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return b}function Ga(a,b,c){var d="",e=p.location.href.split("?");e.length&&(e=Fa(e[1]),b=c||b,e[b]&&(d="&"+a+"="+e[b]));return d};var Ha={};function T(a,b,c){a[b]=a[b]||c}function U(a,b,c){return a[c]?"&g"+b+"="+encodeURIComponent(a[c]):""};var V={b:function(a){a+="=";for(var b=document.cookie.split(";"),c,d=0,e=b.length;d<e;d++){for(c=b[d];c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return c.substring(a.length,c.length)}return""},create:function(a,b,c){var d=p._sf_async_config;if(!d||!d.noCookies)d=new Date,d.setTime(D()+c*864E5),document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"}};V.remove=function(a){V.b(a)&&V.create(a,"",-1)};var W={};W.d=function(a){var b=p._sf_async_config;if(!a&&b&&b.noCookies)return l;if(W.d.T!==h)return W.d.T;var a=D()+"",c,d;try{if((d=p.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return W.d.T=d}catch(e){}return W.d.T=l};W.b=function(a){var b=W.d();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&D()>c)?(W.remove(a),""):b.getItem(a)||""};
W.create=function(a,b,c){var d=W.d();if(d){try{d.setItem(a,b)}catch(e){}b=new Date;b.setTime(D()+c*864E5);try{d.setItem(a+"_expires",b.getTime())}catch(f){}}};W.remove=function(a){var b=W.d();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function X(a){this.L=a||"";this.ca=m;Ia(this)}
function Ia(a){if(!V.b("_cb_ls")){var b=W.d()!==l,c=V.b("_SUPERFLY_nosample");c&&v(["","_v_","_p_"],function(b,d){a.create(d+"_SUPERFLY_nosample",c,0.007,k)});var d=V.b("_chartbeat3");d&&(a.create("_v__chartbeat3",d,30,k),V.remove("_chartbeat3"));b&&((b=V.b("_chartbeat2"))&&a.create("_chartbeat2",b,30,k),(b=V.b("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,30,k),(b=V.b("_chartbeat5"))&&a.create("_chartbeat5",b,6.944444444444445E-4,k));V.create("_cb_ls","1",30)}}
function Ja(a){var b=a.ca;a.ca=m;return b}X.prototype.create=function(a,b,c,d){a=d?a:this.L+a;(W.d()?W:V).create(a,b,c);W.d()&&V.create(a,b,c)};X.prototype.update=function(a,b,c,d,e,f){a=d?a:this.L+a;e=typeof e==="string"?e:"::";d=(d=this.b(a,k))?d.split(e):[];typeof f==="number"&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,k)};
X.prototype.b=function(a,b){var a=b?a:this.L+a,c=(W.d()?W:V).b(a);if(!c&&W.d()&&(c=V.b(a))&&V.b("_cb_ls")){this.ca=k;var d;switch(a){case "_SUPERFLY_nosample":d=0.007;break;case "_chartbeat4":d=0.0417;break;case "_cb_cp":d=0.0417;break;default:d=30}W.create(a,c,d)}return c};X.prototype.remove=function(a,b){a=b?a:this.L+a;(W.d()?W:V).remove(a);W.d()&&V.remove(a)};function s(a){this.a=p._sf_async_config||{};this.va=w(this.Fa,this);this.o=[];this.m=a;this.c=new X(this.oa);this.h();this.ma=w(this.l,this);z(p,"unload",this.ma);for(var a=w(this.Ga,this),b=p._cbq||[];b.length;)a(b.shift());p._cbq={push:a}}o=s.prototype;o.h=function(){this.Z=this.j=0;this.w=D();this.v=t(Ka(this,m));this.u=k;this.ia=72E5;this.i=this.f=0;this.m.h();var a=+this.a.sessionLength;if(!isNaN(a)&&this.oa!=="_p_")this.ia=a*6E4};
function La(a){if(!a.c.b("_SUPERFLY_nosample"))a.Aa?a.ba():(a.Aa=k,!p._sf_async_config&&!p._cbq?(a.la=w(a.ba,a),z(p,"load",a.la)):a.ba())}o.ba=function(){var a=p._sf_startpt,b=p._sf_endpt;if(A(a))this.K=A(b)?b-a:D()-a;this.s=setInterval(w(this.ja,this),15E3);this.ja()};
o.ja=function(){this.i=pa(this.m);this.f+=this.i;var a=this.a.reading&&+this.a.reading||this.i>0;this.Z<this.j&&!a?this.Z++:(a?this.j=0:Ma(this),this.Z=0,this.o.push(0),this.o.length>18&&this.o.shift(),D()-this.w>=this.ia?clearInterval(this.s):this.aa())};function Na(a,b){var c;c=new Image(1,1);c.onerror=a.va;c.src=b}o.Fa=function(){this.o.push(1);for(var a=0,b=0,c=this.o.length;b<c;++b)a+=this.o[b];a<3?(this.u=k,Ma(this)):clearInterval(this.s)};
o.l=function(){this.c.update("_cb_cp",this.v,0.0417,m,",")};o.Ga=function(a){this.a[a[0]]=a[1];this.j=0};function Ma(a){var b=a.j,b=b?Math.min(b*2,16):1;a.j=b}o.q=function(a,b){this.A=p.location.protocol+"//"+this.a.domain+this.a.path;this.a.path=a;b&&(this.a.title=b);clearInterval(this.s);this.l();this.h();La(this)};function Oa(a){if(a.A)return k;a=(document.referrer||"").indexOf("://"+p.location.host+"/");return a!=-1&&a<9}function Pa(a){return encodeURIComponent(a.A||document.referrer||"")}
function Qa(a){a=a.a.title.slice(0,100);return encodeURIComponent(a)}function Ka(a,b){var c=p.navigator,d=p.window.screen,e=[c.userAgent,c.platform,(new Date).getTimezoneOffset(),d.width+d.height+d.colorDepth];v(c.plugins,function(a,b){e.push(b.name+b.description+b.filename+b[0].type)});if(b===m)c=p.performance,e=e.concat([c&&c.now?c.now():"",Pa(a),document.title,p.location.href,D(),O("Width"),P(),ba()]);return e.join()}o.U=function(){fa("load",this.la);fa("unload",this.ma);clearInterval(this.s)};function Y(a,b){this.g=[];this.I=b;"postMessage"in window===k&&z(window,"message",w(this.za,this));this.oa="_p_";s.call(this,a)}aa(Y);var Ra=0;o=Y.prototype;
o.h=function(){Y.z.h.call(this);var a=p.location;T(this.a,"pingServer","ping.chartbeat.net");T(this.a,"title",document.title);T(this.a,"domain",a.host);T(this.a,"path",ea(!!this.a.useCanonical));T(this.a,"engaged",m);a=p.location.search||"";if(a.match(qa))a=Fa(a).__cb_debug,Ra=parseInt(a,10);this.D=this.a.adIdentifier||"data-cb-ad-id";this.a.domain=y(this.a.domain);this.k=this.c.b("_chartbeat2",k);this.V=0;this.xa=function(){this.V&&p.clearTimeout(this.V);this.V=p.setTimeout(w(this.aa,this),50)};
this.wa=H("forcePing",this.xa,this);this.$=this.k?0:1;if(!this.k)this.k=t(Ka(this,m),3);this.k=this.k.split(".")[0];this.da();this.P=H("activity",this.da,this);Sa(this);if((a=this.a.engagedAdFilters)&&a.length){this.a.engagedAdFilters=[];var b=this;v(a,function(a,d){b.C(d)})}this.ua=H("adEngaged",this.ta,this);this.na=[]};
o.l=function(){Y.z.l.call(this);this.i=pa(this.m);this.f+=this.i;var a=!!Ha.scrollElement;this.c.update("_chartbeat4",["t="+this.v,"E="+this.f,"ad="+F(Ta(this)),"x="+M(a),"c="+Math.round((D()-this.w)/600)/100,"y="+P(),"w="+N()].join("&"),0.0417)};
function Ta(a){var b=[];v(a.g.concat(a.na),function(a,d){var e=d.p?d.p():d,f=encodeURIComponent(e.id),g=[e.engagedSeconds,e.positionLeft,e.positionTop,e.width,e.height,encodeURIComponent(e.campaignId||""),encodeURIComponent(e.creativeId||"")];e.refreshed&&g.push("1");b.push(f+"="+g.join("::"))});return b.join("&")}
o.aa=function(){var a=this.a,b=M(!!a.scrollElement),c="",d="";if(this.u)this.u=m,c=(Oa(this)?"&v=":"&r=")+Pa(this),this.A&&(c+="&vp=1"),d="&i="+Qa(this);var e=this.c.b("_cb_cp"),e=e?"&D="+e:"";this.c.remove("_cb_cp");var f="",g=this.c.b("_chartbeat4");g&&(v(g.split("::"),function(a,b){f+="&z="+encodeURIComponent(b)}),this.c.remove("_chartbeat4"));g=this.K?"&b="+this.K:"";ra("[a] ping with path: "+F(ea(!!a.useCanonical)));var i=encodeURIComponent("ads."+a.domain),j=p.location,q=[],r;for(r in a)r.charAt(0)==
"_"&&q.push(r+"="+a[r]);Na(this,(j.protocol||"http:")+"//"+a.pingServer+"/ping/ad?h="+i+"&p="+encodeURIComponent(a.path)+"&u="+this.k+"&d="+F(y(j.host))+"&g="+a.uid+U(a,0,"sections")+U(a,1,"authors")+U(a,2,"zone")+U(a,3,"sponsorName")+"&n="+this.$+"&c="+Math.round((D()-this.w)/600)/100+"&x="+b+"&y="+P()+"&o="+O("Width")+"&w="+N()+"&j="+Math.round((this.j+2)*15E3/1E3)+"&E="+this.f+c+g+"&t="+this.v+"&V=25"+e+d+(Ja(this.c)?"&l=1":"")+(q.length?"&"+q.join("&"):"")+"&ad="+F(Ta(this))+f+"&_")};
function Ua(a){a=ua(a.D,"div");return ha(a,function(a){a=Q(a);return a.height>1&&a.width>1})}o.da=function(){for(var a=Ua(this),b,c=0,d=a.length;c<d;c++)if(!Va(this,a[c])){var e=a[c];b=new Aa(e,this.m,this.I,Ra);this.g.push(b);b.M();if(e=va("data-cb-engaged-seconds",e))b=b.p(k),b.engagedSeconds=parseInt(e,10),this.C(b)}Wa(this)};
function Wa(a){var b=[];v(a.g,function(a,d){var e;typeof document.contains==="function"&&!document.contains(d.e)?e=m:(e=Q(d.e),e=e.height>1&&e.width>1);e===k?b.push(d):d.U()});a.g=b}function Va(a,b){var c=m;v(a.g,function(a,e){if(e.e===b)return c=k,m});return c}o.M=function(){v(this.g,function(a,b){b.M()})};
o.za=function(a){var b=ia(a.data),c=a.source;if(b.cbType==="campaignMessage"){this.da();var a=document.getElementsByTagName("iframe"),d=h;v(a,function(a,b){if(b.contentWindow===c)return d=b,m});var e=d.getAttribute(this.D);if(e===l){a=wa(d,this.D);if(a===m)return;e=a.getAttribute(this.D)}var f=h;v(this.g,function(a,b){if(e===b.r)return f=b,m});if(f!==h){var a=b.campaignId,g=b.creativeId;Ca(f,a,g,k);b.engagedSeconds&&this.C({engagedSeconds:parseInt(b.engagedSeconds,10),id:f.r,campaignId:a,creativeId:g});
"postMessage"in window===k&&d.contentWindow.postMessage("cbdata::ack","*")}}};o.q=function(){J(this.wa);J(this.P);J(this.ua);this.A=p.location.protocol+"//"+this.a.domain+this.a.path;clearInterval(this.s);this.l();v(this.g,function(a,b){b.U()});this.g=[]};
o.C=function(a){if(a&&A(a.engagedSeconds)&&!isNaN(a.engagedSeconds)){var b=this.a.engagedAdFilters;if(!b||b.length===h)this.a.engagedAdFilters=[],b=this.a.engagedAdFilters;var c={};c.engagedSeconds=a.engagedSeconds;v(["id","campaignId","creativeId"],function(b,d){typeof a[d]=="string"&&(c[d]=a[d])});var d=m;v(b,function(a,b){d=ga(b,c);return!d});d||b.push(c)}};
o.ta=function(a,b){var c=this.a.engagedAdCallback;if(c){var d=this.a.engagedAdFilters;if(d&&d.length&&a){var e=a.engagedSeconds;v(d,function(d,g){if(g.engagedSeconds===e){var i=k;v(g,function(b,c){return i=c===a[b]});if(i)return a.element=b,c(a,e),m}})}}};o.Ha=function(a){if(a){var b;v(this.g,function(c,e){if(e.r===a||e.e===a)return b=e,m});if(b){var c=b.p();c.refreshed="1";this.na.push(c);b.reset()}}};
function Sa(a){if(Ra===1){var b=document.createElement("div");b.setAttribute("style","position:fixed; left:0; right:0 ;top:0 ;bottom:0; background-color: rgba(0, 0, 0, 0.3); z-index:1000;");document.body.appendChild(b);var c=document.createElement("div");document.body.appendChild(c);var d=a.a;v(["sections","zone","sponsorName"],function(a,b){if(d[b]!==h){var g=document.createElement("div");g.textContent=b+": "+d[b];c.appendChild(g)}});c.children.length&&c.setAttribute("style","background-color: #F1F7FB; z-index: 9000000; position: fixed;padding: 10px; border-radius: 5px; font-size: 12px;color: #658BA1; border: 1px solid #C8DAE8;font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif;top: "+
Math.round(N()*0.9)+"px;left: "+Math.round(ya("Width")*0.45)+"px;")}};if(!p.pSUPERFLY_pub){var Xa=new Y(new L,new sa);p.pSUPERFLY_pub=Xa;Y.prototype.virtualPage=Y.prototype.q;Y.prototype.addEngagedAdFilter=Y.prototype.C;Y.prototype.refreshAd=Y.prototype.Ha;Y.prototype.updateCampaignData=Y.prototype.M;La(Xa)};var Ya=(document.location.protocol=="https:"?"https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/":"http://static.chartbeat.com/")+"js/inpage.js";function Za(){var a=document.createElement("script");a.async=k;a.src=Ya;var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}function $a(a){if(/[\/|\.]chartbeat\.com$/.test(a.origin)){var b=W.d(k),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Za())}};function Z(a){s.call(this,a);z(document.body,"click",w(this.Ea,this))}aa(Z);o=Z.prototype;
o.h=function(){Z.z.h.call(this);this.S=l;for(var a=this.a,b=document.getElementsByTagName("script"),c=0,d=b.length;c<d;++c)if(b[c].src.match(/chartbeat.js/)){b=Fa(b[c].src.split("?")[1]);T(a,"uid",b.uid);T(a,"domain",b.domain);break}a=p.location;T(this.a,"pingServer","ping.chartbeat.net");T(this.a,"title",document.title);T(this.a,"domain",a.host);T(this.a,"path",ea(!!this.a.useCanonical));this.W=y(a.host);this.a.domain=y(this.a.domain);var a=(this.c.b("_chartbeat2",k)||"").split("."),b=D(),c=b-+(a[1]||
0),e="1",f=a&&+a[2],d=a&&a[3];if(a&&f&&d)if(e=Math.abs((B(b)-B(f))/864E5)){e=Math.min(e,16)-1;for(f="";e--;)f+=0;e=(d+f+"1").slice(-16)}else e=d;d=e;this.$=a[0]&&c>18E5?0:1;a[0]||(a[0]=t(Ka(this,m),3),a[1]=b);a[2]=b;a[3]=d;this.N=a[0];this.k=a.join(".");this.c.create("_chartbeat2",this.k,30,k);this.a.utoken=this.N;var g;b=+a[1];c=+a[2];if((a=a[3])&&b&&c)g=(Math.min((Math.abs((B(c)-B(b))/864E5)||0)+1,16,a.length)-1).toString(16),g+=("0000"+parseInt(a,2).toString(16)).slice(-4);this.fa=g;p.postMessage&&
z(p,"message",w(this.ya,this));this.t=0;this.P=H("activity",this.Ba,this);g=this.c.b("_chartbeat_uuniq")==="3";this.c.create("_chartbeat_uuniq","3",30);g||Na(this,"//ping.chartbeat.net/uuniq?u="+this.N+"&u2="+t(Ka(this,k)))};o.ra=function(a){this.S=a};o.l=function(){Z.z.l.call(this);this.i=pa(this.m);this.f+=this.i;this.c.update("_chartbeat4",["t="+this.v,"E="+this.f,"x="+M(!!this.a.scrollElement),"c="+Math.round((D()-this.w)/600)/100,"y="+P(),"w="+N()].join("&"),0.0417)};
o.aa=function(){var a=this.a,b=M(!!this.a.scrollElement);this.t=Math.max(this.t,b);var c=Math.round((D()-this.w)/600)/100,d=0,e=0,f=0;oa(this.m,"onkeydown")?e=1:this.a.reading&&+this.a.reading||this.i>0||c<0.09?d=1:f=1;var g="",i="",j="",q="",r="",x=Oa(this);if(this.u){this.u=m;var g=(x?"&v=":"&r=")+Pa(this),i="&i="+Qa(this),C=this.a.hudTrackable;C!==h&&(j="&L="+(C?"1":"0"));if(x&&(x=ab(this)))g="&v="+encodeURIComponent(x.path),q="&K="+x.left+"::"+x.top,x.ka>1&&(q+="&l1="+x.ka);a.alias&&(r="&PA="+
encodeURIComponent(a.alias));this.A&&(g+="&vp=1")}var x=this.K?"&b="+this.K:"",C=this.S?"&A="+this.S:"",I=this.fa?"&f="+this.fa:"",E=this.c.b("_cb_cp"),E=E?"&D="+E:"";this.c.remove("_cb_cp");var u="",n=this.c.b("_chartbeat4");n&&(v(n.split("::"),function(a,b){u+="&z="+encodeURIComponent(b)}),this.c.remove("_chartbeat4"));var n=[],da;for(da in a)da.charAt(0)=="_"&&n.push(da+"="+a[da]);Na(this,(p.location.protocol||"http:")+"//"+a.pingServer+"/ping?h="+encodeURIComponent(a.domain)+"&p="+encodeURIComponent(a.path)+
"&u="+this.N+"&d="+encodeURIComponent(this.W)+"&g="+a.uid+U(a,0,"sections")+U(a,1,"authors")+U(a,3,"sponsorName")+(a.noCookies?"":"&n="+this.$)+I+"&c="+c+"&x="+b+"&m="+this.t+"&y="+P()+"&o="+O("Width")+"&w="+N()+"&j="+Math.round((this.j+2)*15E3/1E3)+"&R="+d+"&W="+e+"&I="+f+"&E="+this.f+"&e="+this.i+g+q+r+x+C+Ga("C","utm_campaign",a.campaignTag)+Ga("M","utm_medium",a.mediumTag)+"&t="+this.v+"&V=25"+E+u+i+j+(Ja(this.c)?"&l=1":"")+(n.length?"&"+n.join("&"):"")+"&_")};
o.ya=function(a){var b=this.a;if(a.origin==="http://"+(b.playerdomain||this.W)){var c=a.data;if(typeof c=="string"&&c.indexOf("cbqpush::")===0){if(a=c.split("::"),a.length==3)a[1].indexOf("_")===0&&(b[a[1]]=a[2]),this.j=0}else c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&path="+encodeURIComponent(b.path)+"&title="+Qa(this)+"&referrer="+Pa(this)+"&internal="+(Oa(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.W)+"&utoken="+this.N,a.source.postMessage(b,"*"))}};
o.Ea=function(a){if(a=a||window.event){var b=a.target||a.srcElement;if(b.tagName!=="A")if(b.parentNode)if(b.parentNode.tagName==="A")b=b.parentNode;else if(b.parentNode.parentNode&&b.parentNode.parentNode.tagName==="A")b=b.parentNode.parentNode;else return;else return;a=b.href||"";a=a.replace(/-{2,}/g,"-");var c=a,d="",e="";if(c){var e=document.createElement("a"),f=p.location;c.indexOf("http")!==0&&c.indexOf("javascript")!==0&&(c=f.protocol+c);e.href=c;d=e.hostname;e=e.protocol;if(d==="")d=f.hostname;
if(e==="")e=f.protocol;e==="javascript:"&&(d="")}d!==p.location.hostname||e==="javascript:"||(b=R(b,h,k),this.c.update("_chartbeat5",[b.x,b.y,encodeURIComponent(this.a.path),encodeURIComponent(a)].join(","),6.944444444444445E-4,m,h,5))}};o.Ba=function(){var a=M(!!this.a.scrollElement);this.t=Math.max(this.t,a)};o.q=function(a,b){J(this.P);Z.z.q.call(this,a,b)};
function ab(a){var b=a.c.b("_chartbeat5");if(!b)return l;var b=b.split("::"),c=b.length,d,e;if(c===1)d=b[0].split(","),e=0;else{var f,g=p.location.href;v(b,function(a,b){var c=b.split(","),r=ja(g,decodeURIComponent(c[3]));if(r===0)return d=c,e=a,m;if(f===h||r<f)f=r,d=c,e=a})}b.splice(e,1);a.c.create("_chartbeat5",b.join("::"),6.944444444444445E-4);return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),ka:c}};if(!p.pSUPERFLY){var bb=new Z(new L);p.pSUPERFLY=bb;Z.prototype.virtualPage=Z.prototype.q;Z.prototype.activity=Z.prototype.ra;var $=p.pSUPERFLY_pub;$&&$.virtualPage&&(Z.prototype.virtualPage=function(){var a=arguments.length?Array.prototype.slice.call(arguments,0):[];$.virtualPage();Z.prototype.q.apply(bb,a);$.h();La($)});$&&$.addEngagedAdFilter&&(Z.prototype.addEngagedAdFilter=w($.addEngagedAdFilter,$));$&&$.refreshAd&&(Z.prototype.refreshAd=w($.refreshAd,$));La(bb);var cb=W.d(k);cb&&(z(p,"message",
$a),cb.getItem("_cb_ip")&&Za())};})();
